version: '3'
services:
  mysql:
    image: mysql:5.7.37
    container_name: mysql-server
    restart: always
    volumes:
      - 'mysql_data:/var/lib/mysql'
      - './schema:/docker-entrypoint-initdb.d'
    environment:
      MYSQL_USER: dbadmin
      MYSQL_PASSWORD: BcGH2Gj41J5VF1
      MYSQL_ROOT_PASSWORD: BcGH2Gj41J5VF1
      MYSQL_DATABASE: tabsquare
    networks:
      - app-network
  app-server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    environment:
      - APP_DB_USERNAME=dbadmin
      - APP_DB_PASSWORD=BcGH2Gj41J5VF1
    networks:
      - app-network

volumes:
  mysql_data:
    driver: local
networks:
  app-network:
    driver: bridge