version: '3'
services:

# Pull and run mysql from docker hub image
# Mount data volume and run database schema required for our app
# Set Mysql user details and database name
  mysql:
    image: mysql:5.7.37
    container_name: mysql-server
    restart: always
    volumes:
      - 'mysql_data:/var/lib/mysql'
      - './schema:/docker-entrypoint-initdb.d'
    environment:
      MYSQL_USER: dbadm
      MYSQL_PASSWORD: BcGH2Gj41J5VF1
      MYSQL_ROOT_PASSWORD: BcGH2Gj41J5VF1
      MYSQL_DATABASE: ksar
    networks:
      - app-network

# App server image is built from Dockerfile at startup
# Expose port 8080 to host port 80
# Set dependency on mysql database
# Set Database user & password
  app-server:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - '80:8080'
    depends_on:
      - mysql
    environment:
      - APP_DB_USERNAME=dbadmin
      - APP_DB_PASSWORD=BcGH2Gj41J5VF1
    networks:
      - app-network

volumes:
  mysql_data:
    driver: local
networks:
  app-network:
    driver: bridge