apiVersion: v2
name: ksar-app
description: A Helm chart for Ksar App

type: application

version: 0.1.0

appVersion: "1.0.1"

dependencies:
  - name: mysql
    version: 1.6.x
    repository: https://charts.helm.sh/stable
    condition: mysql.enabled
    tags:
      - mysql-database
